### PR TITLE
changed: Updated DryIoc to 2.0.0

### PR DESCRIPTION
**Pull request by dadhi**
Hello,

I have update to DryIoc 2.0.0 release.
The build is fine. But running the Runner project fails with error from attachment. Something with this IP:

> No connection could be made because the target machine actively refused it 217.70.184.38:80

Could you look into it?

[net-feature-tests-error.txt](https://github.com/ashmind/net-feature-tests/files/41375/net-feature-tests-error.txt)

### CODE REVIEW

**Comment by dadhi** [comment]
Hello @ashmind, 
did you have a chance to look?

**Comment by ashmind** [comment]
@dadhi Yes, actually I thought I already merged it.
When I run the runner some tests that weren't failing before for DryIoc are falling now -- is that intentional?

Tests are *ConstrainsForOpenGenerics*:
```
System.ArgumentException: Type FeatureTests.On.DependencyInjection.TestTypes.GenericService`1[T] contains generic parameters
       at System.Dynamic.Utils.TypeUtils.ValidateType(Type type)
       at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
       at DryIoc.ReflectionFactory.CreateServiceExpression(MemberInfo ctorOrMethodOrMember, Expression factoryExpr, Expression[] paramExprs, Request request)
       at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
       at DryIoc.Factory.GetExpressionOrDefault(Request request)
       at DryIoc.Factory.GetDelegateOrDefault(Request request)
       at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, Boolean ifUnresolvedReturnDefault, Type requiredServiceType, RequestInfo preResolveParent, IScope scope)
       at DryIoc.Container.ResolveMany>d__29.MoveNext()
       at System.Linq.Enumerable.<CastIterator>d__1`1.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)    
```

Also all request scope tests.

**Comment by dadhi** [comment]
Nope, this errors should not be here. I will check on my side. But did you know what was the error with IP?

**Comment by ashmind** [comment]
Hard to say, seems like on of the license locations was down -- when I ran it I didn't get that issue so I don't know which one.

Later I'll catch those exceptions as license info is non-essential -- but haven't got to that yet.

**Comment by dadhi** [comment]
Ok, I will recheck this on my side.

**Comment by dadhi** [comment]
I have fixed ArgEx for OpenGenConstraints in DryIoc. Will close this for now, and submit another one with new ver, and working setup for scoped resolutions.

**Pull request closed without merging**
