### PR TITLE
Updated special case messages for Simple Injector.

### PR DESCRIPTION
**Pull request by dotnetjunkie**
Updated the special case messages for Simple Injector:
 - Replaced the ugly bit.ly links with links to simpleinjector.org.
 - Replaced the multi-line text with concatenated text. This makes the text format correctly in a title popup in html.

Upgraded to Simple Injector 2.7.3.

### CODE REVIEW

**Comment by ashmind** [comment]
Thanks for that -- but can you submit one without concatenation?
I'd rather fix UI bug than work around it in the source.

**Comment by dotnetjunkie** [comment]
Of course. I thought that the concatenation would make it easier for you (since you wouldn't have to fix anything else). I'll send a new PR.

**Comment by ashmind** [comment]
Sure -- but I don't mind extra work if the end result is neater :)
I'll take a look at a new one tomorrow.

**Comment by dotnetjunkie** [comment]
I agee; it is neater.

**Comment by dotnetjunkie** [comment]
Fixed.

**Pull request merged**
